---

# This playbook is used to deploy student-list application based on Docker

# build and push builded images

- name: Log into DockerHub
  docker_login:
    username: "{{ docker_hub_login }}"
    email: "{{ docker_hub_email }}"
    password: "{{ docker_hub_password }}"
- name: create project directory
  file:
    path: "{{home}}/fake-backend "
    state: directory
- name: copy fake-backend private key file
  copy:
    content: '{{ github_private_key }}'
    dest: "{{home}}/.ssh/id_rsa"
    owner: centos

- name: Retrieve fake-backend  addons source code
  git:
    repo: "{{ fake-backend _source_repo  }}"
    dest: "{{ home }}/fake-backend "
    accept_hostkey: yes
    force: yes
    recursive: no
    key_file: "{{ home }}/.ssh/id_rsa"
    version: "{{ fake-backend_source_branch }}"

- name: Build api image and push it to Docker Hub
  docker_image:
    path: "{{ home }}/fake-backend"
    name: "{{ docker_hub_login }}/fake-backend-api"
    push: yes
    tag: "{{fake-backend_docker_image_tag}}"

# docker network 

- name: crete docker network to interconnect containers
  docker_network:
    name: fake-backend_network 

# deploy api

- name: Deploy api
  docker_container:
    name: mysql:5.7
    image: "{{ docker_hub_login }}/fake-backend-api:{{fake-backend_docker_image_tag}}"
    state: started
    volumes:
   #  - "{{ home }}/student-list/simple_api/student_age.json:/data/student_age.json"
	  - mysql_config:/var/lib/mysql 
	env:
      - MYSQL_ROOT_PASSWORD=rootpwdfrank
      - MYSQL_DATABASE=battleboat
      - MYSQL_USER=battleuser
      - MYSQL_PASSWORD=battlepass
    restart: always
     networks:
     - name: fake-backend_network 
 # ports:
 #  - "4000:5000"

# deploy frontend

- name: Deploy frontend
  docker_container:
    name: frontend
    image: fake-backend:latest
    state: started
     networks:
      - name: fake-backend_network
    volumes:
#      - "{{ home }}/student-list/website:/var/www/html"
	  - ./static_files:/etc/backend/static
	restart: always  
    env:
     - DATABASE_HOST=dbfrank
     - DATABASE_PORT=3306
     - DATABASE_USER=battleuser
     - DATABASE_PASSWORD=battlepass
     - DATABASE_NAME=battleboat
    ports:
      - "8181:3000"
  volumes:
  mysql_config:    
